// <auto-generated />
using System;
using Jasmine.FastenerDepartment.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Jasmine.FastenerDepartment.EF.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260518152047_AddLocalization")]
    partial class AddLocalization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Jasmine.FastenerDepartment.Domain.HistoryEntries.Models.ProductHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChangeReasonCode")
                        .HasColumnType("integer")
                        .HasColumnName("ChangeReasonId");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChangeReasonCode");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductHistoryEntries", (string)null);
                });

            modelBuilder.Entity("Jasmine.FastenerDepartment.Domain.MeasurementUnits.Models.MeasurementUnit", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("MeasurementUnits", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "{\"En\":\"Pieces\",\"Ru\":\"Штуки\"}",
                            ShortName = "{\"En\":\"pcs\",\"Ru\":\"шт\"}"
                        },
                        new
                        {
                            Id = 2,
                            Name = "{\"En\":\"Meters\",\"Ru\":\"Метры\"}",
                            ShortName = "{\"En\":\"m\",\"Ru\":\"м\"}"
                        },
                        new
                        {
                            Id = 3,
                            Name = "{\"En\":\"Kilograms\",\"Ru\":\"Килограммы\"}",
                            ShortName = "{\"En\":\"kg\",\"Ru\":\"кг\"}"
                        },
                        new
                        {
                            Id = 4,
                            Name = "{\"En\":\"Packages\",\"Ru\":\"Упаковки\"}",
                            ShortName = "{\"En\":\"pack\",\"Ru\":\"уп\"}"
                        },
                        new
                        {
                            Id = 5,
                            Name = "{\"En\":\"Sets\",\"Ru\":\"Комплекты\"}",
                            ShortName = "{\"En\":\"sets\",\"Ru\":\"компл\"}"
                        },
                        new
                        {
                            Id = 6,
                            Name = "{\"En\":\"Lists\",\"Ru\":\"Листы\"}",
                            ShortName = "{\"En\":\"l\",\"Ru\":\"л\"}"
                        });
                });

            modelBuilder.Entity("Jasmine.FastenerDepartment.Domain.Orders.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("StatusId");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("StatusCode");

                    b.HasIndex("SupplierId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("Jasmine.FastenerDepartment.Domain.Orders.Models.OrderHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("OrderStatusId");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("OrderStatusCode");

                    b.ToTable("OrderHistoryEntries", (string)null);
                });

            modelBuilder.Entity("Jasmine.FastenerDepartment.Domain.Orders.Models.OrderProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsFulfilled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("SupplierProductNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProducts", (string)null);
                });

            modelBuilder.Entity("Jasmine.FastenerDepartment.Domain.Orders.Models.OrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("OrderStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "{\"En\":\"Created\",\"Ru\":\"Создан\"}"
                        },
                        new
                        {
                            Id = 2,
                            Name = "{\"En\":\"Sent\",\"Ru\":\"Отправлен\"}"
                        },
                        new
                        {
                            Id = 3,
                            Name = "{\"En\":\"Fulfilled\",\"Ru\":\"Доставлен\"}"
                        },
                        new
                        {
                            Id = 4,
                            Name = "{\"En\":\"Cancelled\",\"Ru\":\"Отменен\"}"
                        });
                });

            modelBuilder.Entity("Jasmine.FastenerDepartment.Domain.PriceTags.Models.PriceTag", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("PriceTags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "{\"En\":\"Size S\",\"Ru\":\"Размер S\"}"
                        },
                        new
                        {
                            Id = 3,
                            Name = "{\"En\":\"Size L\",\"Ru\":\"Размер L\"}"
                        },
                        new
                        {
                            Id = 4,
                            Name = "{\"En\":\"Size M\",\"Ru\":\"Размер M\"}"
                        },
                        new
                        {
                            Id = 5,
                            Name = "{\"En\":\"Size XL\",\"Ru\":\"Размер XL\"}"
                        });
                });

            modelBuilder.Entity("Jasmine.FastenerDepartment.Domain.ProductTypes.Models.ProductType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes", (string)null);
                });

            modelBuilder.Entity("Jasmine.FastenerDepartment.Domain.Products.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasHardwareSize")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHardwareSizeEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNeededToOrder")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNeededToPrint")
                        .HasColumnType("boolean");

                    b.Property<int>("MeasurementUnitCode")
                        .HasColumnType("integer")
                        .HasColumnName("MeasurementUnitId");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PriceTagCode")
                        .HasColumnType("integer")
                        .HasColumnName("PriceTagId");

                    b.Property<Guid?>("TypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementUnitCode");

                    b.HasIndex("PriceTagCode");

                    b.HasIndex("TypeId");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("Jasmine.FastenerDepartment.Domain.Products.Models.ProductChangeReason", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("ProductChangeReasons", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "{\"En\":\"Created\",\"Ru\":\"Создан\"}"
                        },
                        new
                        {
                            Id = 2,
                            Description = "{\"En\":\"Changing the number\",\"Ru\":\"Изменение артикула\"}"
                        },
                        new
                        {
                            Id = 3,
                            Description = "{\"En\":\"Changing the name\",\"Ru\":\"Изменение названия\"}"
                        },
                        new
                        {
                            Id = 4,
                            Description = "{\"En\":\"Changing the price\",\"Ru\":\"Изменение цены\"}"
                        },
                        new
                        {
                            Id = 5,
                            Description = "{\"En\":\"Changing the price tag size\",\"Ru\":\"Изменение размера ценника\"}"
                        },
                        new
                        {
                            Id = 6,
                            Description = "{\"En\":\"Changing the measurement unit\",\"Ru\":\"Изменение единицы измерения\"}"
                        },
                        new
                        {
                            Id = 7,
                            Description = "{\"En\":\"Changing the order status\",\"Ru\":\"Изменение статуса заказа\"}"
                        },
                        new
                        {
                            Id = 8,
                            Description = "{\"En\":\"Changing the print status\",\"Ru\":\"Изменение статуса печати\"}"
                        },
                        new
                        {
                            Id = 9,
                            Description = "{\"En\":\"Deleted\",\"Ru\":\"Удален\"}"
                        },
                        new
                        {
                            Id = 10,
                            Description = "{\"En\":\"Recovered\",\"Ru\":\"Восстановлен\"}"
                        },
                        new
                        {
                            Id = 11,
                            Description = "{\"En\":\"Changing the type\",\"Ru\":\"Изменение типа\"}"
                        });
                });

            modelBuilder.Entity("Jasmine.FastenerDepartment.Domain.Settings.Models.SettingsEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Settings", (string)null);
                });

            modelBuilder.Entity("Jasmine.FastenerDepartment.Domain.Suppliers.Models.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Suppliers", (string)null);
                });

            modelBuilder.Entity("Jasmine.FastenerDepartment.Domain.Suppliers.Models.SupplierProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SupplierId");

                    b.ToTable("SupplierProducts", (string)null);
                });

            modelBuilder.Entity("Jasmine.FastenerDepartment.Domain.HistoryEntries.Models.ProductHistoryEntry", b =>
                {
                    b.HasOne("Jasmine.FastenerDepartment.Domain.Products.Models.ProductChangeReason", "Reason")
                        .WithMany()
                        .HasForeignKey("ChangeReasonCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Jasmine.FastenerDepartment.Domain.Products.Models.Product", "Product")
                        .WithMany("HistoryEntries")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Reason");
                });

            modelBuilder.Entity("Jasmine.FastenerDepartment.Domain.Orders.Models.Order", b =>
                {
                    b.HasOne("Jasmine.FastenerDepartment.Domain.Orders.Models.OrderStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jasmine.FastenerDepartment.Domain.Suppliers.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Status");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Jasmine.FastenerDepartment.Domain.Orders.Models.OrderHistoryEntry", b =>
                {
                    b.HasOne("Jasmine.FastenerDepartment.Domain.Orders.Models.Order", null)
                        .WithMany("HistoryEntries")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jasmine.FastenerDepartment.Domain.Orders.Models.OrderStatus", null)
                        .WithMany()
                        .HasForeignKey("OrderStatusCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jasmine.FastenerDepartment.Domain.Orders.Models.OrderProduct", b =>
                {
                    b.HasOne("Jasmine.FastenerDepartment.Domain.Orders.Models.Order", null)
                        .WithMany("Products")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jasmine.FastenerDepartment.Domain.Products.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("Jasmine.FastenerDepartment.Domain.Common.Models.Quantity", "Fulfilled", b1 =>
                        {
                            b1.Property<Guid>("OrderProductId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("MeasurementUnitCode")
                                .HasColumnType("integer")
                                .HasColumnName("FulfilledMeasurementUnitId");

                            b1.Property<string>("SpecialMeasurementUnit")
                                .HasColumnType("varchar(100)")
                                .HasColumnName("FulfilledSpecialMeasurementUnit");

                            b1.Property<double>("Value")
                                .HasColumnType("double precision")
                                .HasColumnName("FulfilledQuantity");

                            b1.HasKey("OrderProductId");

                            b1.ToTable("OrderProducts");

                            b1.WithOwner()
                                .HasForeignKey("OrderProductId");
                        });

                    b.OwnsOne("Jasmine.FastenerDepartment.Domain.Common.Models.Quantity", "Ordered", b1 =>
                        {
                            b1.Property<Guid>("OrderProductId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("MeasurementUnitCode")
                                .HasColumnType("integer")
                                .HasColumnName("OrderedMeasurementUnitId");

                            b1.Property<string>("SpecialMeasurementUnit")
                                .HasColumnType("varchar(100)")
                                .HasColumnName("OrderedSpecialMeasurementUnit");

                            b1.Property<double>("Value")
                                .HasColumnType("double precision")
                                .HasColumnName("OrderedQuantity");

                            b1.HasKey("OrderProductId");

                            b1.ToTable("OrderProducts");

                            b1.WithOwner()
                                .HasForeignKey("OrderProductId");
                        });

                    b.OwnsOne("Jasmine.FastenerDepartment.Domain.Common.Models.Name", "ProductName", b1 =>
                        {
                            b1.Property<Guid>("OrderProductId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ProductName");

                            b1.HasKey("OrderProductId");

                            b1.ToTable("OrderProducts");

                            b1.WithOwner()
                                .HasForeignKey("OrderProductId");
                        });

                    b.Navigation("Fulfilled");

                    b.Navigation("Ordered");

                    b.Navigation("Product");

                    b.Navigation("ProductName");
                });

            modelBuilder.Entity("Jasmine.FastenerDepartment.Domain.ProductTypes.Models.ProductType", b =>
                {
                    b.OwnsOne("Jasmine.FastenerDepartment.Domain.Common.Models.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("ProductTypeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("varchar(500)")
                                .HasColumnName("Name");

                            b1.HasKey("ProductTypeId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("ProductTypes");

                            b1.WithOwner()
                                .HasForeignKey("ProductTypeId");
                        });

                    b.Navigation("Name");
                });

            modelBuilder.Entity("Jasmine.FastenerDepartment.Domain.Products.Models.Product", b =>
                {
                    b.HasOne("Jasmine.FastenerDepartment.Domain.MeasurementUnits.Models.MeasurementUnit", "MeasurementUnit")
                        .WithMany()
                        .HasForeignKey("MeasurementUnitCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jasmine.FastenerDepartment.Domain.PriceTags.Models.PriceTag", "PriceTag")
                        .WithMany()
                        .HasForeignKey("PriceTagCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jasmine.FastenerDepartment.Domain.ProductTypes.Models.ProductType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("Jasmine.FastenerDepartment.Domain.Common.Models.Price", "Price", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Price");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("Jasmine.FastenerDepartment.Domain.Common.Models.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("varchar(500)")
                                .HasColumnName("Name");

                            b1.HasKey("ProductId");

                            b1.HasIndex("Value");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("Jasmine.FastenerDepartment.Domain.Products.Models.ProductNumber", "Number", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("Number");

                            b1.HasKey("ProductId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("MeasurementUnit");

                    b.Navigation("Name");

                    b.Navigation("Number");

                    b.Navigation("Price");

                    b.Navigation("PriceTag");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Jasmine.FastenerDepartment.Domain.Suppliers.Models.Supplier", b =>
                {
                    b.OwnsOne("Jasmine.FastenerDepartment.Domain.Common.Models.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("SupplierId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("varchar(500)")
                                .HasColumnName("Name");

                            b1.HasKey("SupplierId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Suppliers");

                            b1.WithOwner()
                                .HasForeignKey("SupplierId");
                        });

                    b.Navigation("Name");
                });

            modelBuilder.Entity("Jasmine.FastenerDepartment.Domain.Suppliers.Models.SupplierProduct", b =>
                {
                    b.HasOne("Jasmine.FastenerDepartment.Domain.Products.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jasmine.FastenerDepartment.Domain.Suppliers.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Jasmine.FastenerDepartment.Domain.Orders.Models.Order", b =>
                {
                    b.Navigation("HistoryEntries");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Jasmine.FastenerDepartment.Domain.Products.Models.Product", b =>
                {
                    b.Navigation("HistoryEntries");
                });

            modelBuilder.Entity("Jasmine.FastenerDepartment.Domain.Suppliers.Models.Supplier", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
