<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
	  <EnableWindowsTargeting>true</EnableWindowsTargeting>
	  <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Jasmine.FastenerDepartment.Templates.Html\Jasmine.FastenerDepartment.Templates.Html.csproj" />
	  <ProjectReference Include="..\Jasmine.FastenerDepartment.Templates.OfficeDocuments\Jasmine.FastenerDepartment.Templates.OfficeDocuments.csproj" />
	</ItemGroup>

</Project>
